# Alacritty Configuration

[colors.primary]
background = "0x11111b"
foreground = "#ffffff"

[colors.selection]
text = "#000000"

[[colors.indexed_colors]]
color = "#FE640B"
index = 16

[[colors.indexed_colors]]
color = "#DC8A78"
index = 17

[colors.bright]
black = "#6C6F85"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#BCC0CC"
yellow = "#DF8E1D"

[colors.dim]
black = "#5C5F77"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[colors.normal]
black = "#5C5F77"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Inconsolata"
style = "Italic"

[font.normal]
family = "Inconsolata"
style = "Regular"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.85
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 15
y = 12
